# Extra Learning Milestones for Assignment 

# 1. Python

In [1]:
# NumPy  
# Dictionary or Lists 

In [2]:
#For this I am using Numpy to find the engagement rate of 5 Twitter accounts
#The details of the account are in a list below
#They take the format; author, total posts, total engagements

In [3]:
import numpy as np

twitteraccounts = [["author 1", 39, 5832],
                  ["author 2", 38, 5754],
                  ["author 3", 35, 9069],
                  ["author 4", 29, 2004],
                  ["author 5", 17, 1793]]
twitteraccounts

[['author 1', 39, 5832],
 ['author 2', 38, 5754],
 ['author 3', 35, 9069],
 ['author 4', 29, 2004],
 ['author 5', 17, 1793]]

In [4]:
#In order to figure out the engagement rate of each author = 
#I divide total engagements by total posts using Numpy.

In [5]:
posts = [39, 38, 35, 29, 17]
np_posts = np.array(posts)
np_posts

array([39, 38, 35, 29, 17])

In [6]:
engagements = [5832, 5754, 9069, 2004, 1793]
np_engagements = np.array(engagements)
np_engagements

array([5832, 5754, 9069, 2004, 1793])

In [7]:
engagement_rate = np_engagements / np_posts
engagement_rate

array([149.53846154, 151.42105263, 259.11428571,  69.10344828,
       105.47058824])

In [8]:
#Author 3 had the highest engagement rate, earning almost 260 engagements per tweet sent.
#Author 4 had the lowest engagement rate, earning almost 70 engagements per tweet sent.

In [9]:
np.mean(engagement_rate)

146.9295672790965

In [10]:
#The average engagement per post was 146. 
#Subset the data to see how many accounts were above average.

In [11]:
engagement_rate>146

array([ True,  True,  True, False, False])

In [12]:
#Three accounts had an engagement rate of over 146 - Author 1, Author 2, Author 3

In [13]:
engagement_rate[engagement_rate>146]

array([149.53846154, 151.42105263, 259.11428571])

# 2. API - Alpha Vantage

In [14]:
#1. "Your project should make use of one or more of the following: Relational database, API or web scraping"

In [15]:
#Using the Alpha Vantage API to obtain data

TIME SERIES INTRADAY - IBM

In [16]:
import requests
url = 'https://www.alphavantage.co/query?function=TIME_SERIES_INTRADAY&symbol=IBM&interval=5min&apikey=2YK4BESUBA7MKVEW'
r = requests.get(url)
data = r.json()

print(data)

{'Meta Data': {'1. Information': 'Intraday (5min) open, high, low, close prices and volume', '2. Symbol': 'IBM', '3. Last Refreshed': '2022-03-22 20:00:00', '4. Interval': '5min', '5. Output Size': 'Compact', '6. Time Zone': 'US/Eastern'}, 'Time Series (5min)': {'2022-03-22 20:00:00': {'1. open': '129.0600', '2. high': '129.0600', '3. low': '129.0600', '4. close': '129.0600', '5. volume': '138'}, '2022-03-22 19:50:00': {'1. open': '129.3000', '2. high': '129.3000', '3. low': '129.3000', '4. close': '129.3000', '5. volume': '901'}, '2022-03-22 19:45:00': {'1. open': '129.2500', '2. high': '129.3000', '3. low': '129.2500', '4. close': '129.3000', '5. volume': '1000'}, '2022-03-22 16:15:00': {'1. open': '129.1400', '2. high': '129.1400', '3. low': '129.1400', '4. close': '129.1400', '5. volume': '200'}, '2022-03-22 16:05:00': {'1. open': '129.0600', '2. high': '129.0600', '3. low': '129.0600', '4. close': '129.0600', '5. volume': '40393'}, '2022-03-22 16:00:00': {'1. open': '128.9900', '2

COMPANY OVERVIEW - IBM

In [17]:
import requests

url = 'https://www.alphavantage.co/query?function=OVERVIEW&symbol=IBM&apikey=2YK4BESUBA7MKVEW'
r = requests.get(url)
data = r.json()

print(data)

{'Symbol': 'IBM', 'AssetType': 'Common Stock', 'Name': 'International Business Machines Corporation', 'Description': 'International Business Machines Corporation (IBM) is an American multinational technology company headquartered in Armonk, New York, with operations in over 170 countries. The company began in 1911, founded in Endicott, New York, as the Computing-Tabulating-Recording Company (CTR) and was renamed International Business Machines in 1924. IBM is incorporated in New York. IBM produces and sells computer hardware, middleware and software, and provides hosting and consulting services in areas ranging from mainframe computers to nanotechnology. IBM is also a major research organization, holding the record for most annual U.S. patents generated by a business (as of 2020) for 28 consecutive years. Inventions by IBM include the automated teller machine (ATM), the floppy disk, the hard disk drive, the magnetic stripe card, the relational database, the SQL programming language, th

Realtime Exchange Rates; EUR to USD + ETH to BTC

In [18]:
import requests

url = 'https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&from_currency=EUR&to_currency=USD&apikey=2YK4BESUBA7MKVEW'
r = requests.get(url)
data = r.json()

data

{'Realtime Currency Exchange Rate': {'1. From_Currency Code': 'EUR',
  '2. From_Currency Name': 'Euro',
  '3. To_Currency Code': 'USD',
  '4. To_Currency Name': 'United States Dollar',
  '5. Exchange Rate': '1.10095790',
  '6. Last Refreshed': '2022-03-23 17:51:01',
  '7. Time Zone': 'UTC',
  '8. Bid Price': '1.10095790',
  '9. Ask Price': '1.10095790'}}

In [19]:
import requests

url = 'https://www.alphavantage.co/query?function=CURRENCY_EXCHANGE_RATE&from_currency=ETH&to_currency=BTC&apikey=2YK4BESUBA7MKVEW'
r = requests.get(url)
data = r.json()

data

{'Realtime Currency Exchange Rate': {'1. From_Currency Code': 'ETH',
  '2. From_Currency Name': 'Ethereum',
  '3. To_Currency Code': 'BTC',
  '4. To_Currency Name': 'Bitcoin',
  '5. Exchange Rate': '0.07051100',
  '6. Last Refreshed': '2022-03-23 17:51:04',
  '7. Time Zone': 'UTC',
  '8. Bid Price': '0.07051100',
  '9. Ask Price': '0.07051200'}}